const colleges = [
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Applied Electronics",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Electronic and Communication Engineering",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "IT",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Automobile Engineering",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "M-DIT",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "M-DIT",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "M-DIT",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "M-DIT",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "M-DIT",
    dept: "electronics And Computer Engineering",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "M-DIT",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "M-DIT",
    dept: "Electrical And Computer Engineering",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "M-DIT",
    dept: "Cyber security",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Computer Science And Design",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Chemical Engineering",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Applied Electronics And Instrumentation",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "GOVERNMENT ENGINEERING COLLEGE KOZHIKODE",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "KMCT COLLEGE OF ENGINEERING FOR WOMENS",
    dept: "Biomedical Engineering",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Information Technology",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "COLLEGE OF ENGINEERING VADAKARA",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    dept: "Cyber security",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "KMCT INSTITUTE OF EMERGING TECHNOLOGY & MANAGEMENT",
    dept: "Artifical Intelligence & Data Science",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Biotechnology",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Engineering Physics",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Chemical Engineering",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Materials Science And Engineering",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "NATIONAL INSTITUTE OF TECHNOLOGY",
    dept: "Production Engineering",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "AWH ENGINEERING COLLEGE",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Computer Science And Engineering",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Biotechnology",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Computer Science And Engineering(AI & ML)",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Applied Electronics And Instrumentation",
    location: "CALICUT",
    gpa: "76.00%",
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Mechanical Engineering",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Electrical And Electronics Engineering",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Electronics and Communication Engineering",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "VEDAVYASA INSTITUTE OF TECHNOLOGY",
    dept: "Civil Engineering",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "",
    dept: "",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "A.V ABDURAHIMAN ARTS & SCIENCE COLLEGE,KULUPPA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "AL IRSHAD ARTS & SCIENCE COLLEGE FOR WOMEN,THECHIYAD,KALLURUTTY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "AL-FURQAN ARABIC COLLEGE,NADAPURAM",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "ALPHONSA COLLEGE THIRUVAMBADY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    dept: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    dept: "B.Sc GENETICS",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "47.00%",
  },
  {
    name: "AWH SPECIAL COLLEGE,KALLAI,CALICUT",
    dept: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "BAITHUL IZZA ARABIC COLLEGE,NARIKKUNI",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: "48.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "BA COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "47.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "BAITHUL IZZA ARTS & SCIENCE COLLEGE,NARIKKUNI",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "C.K.G MEMORIAL GOVT COLLEGE,PERAMBRA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "CALICUT UNIVERSITY CENTRE FOR COSTUME & FASHION DESIGNING",
    dept: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "CENTRE FOR COMPUTER SCIENCE & INFORMATION TECHNOLOGY",
    dept: "B.Sc INFORMATION TECHNOLOGY",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: "76.00%",
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "CHKM GOVT.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "CO-OPERATIVE ARTS & SCIENCE COLLEGE KURIKKILAD,VADAKARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KALLACHI,NADAPURAM",
    dept: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KILIYANAD",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "76.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,KORANGAD",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    dept: "B.Sc ELECTRONICS",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "COLLEGE OF APPLIED SCIENCE,THIRUVAMPADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "CSI CHRISTIAN MULLER WOMENS COLLEGE,CHOMBALA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "DARUL HUDA ARTS AND SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "DARUNNUJOOM COLLEGE OF ARTS & SCIENCE,PERAMRA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "DARUL MA-RIFA ARABIC COLLEGE,ODUNGAKAD,PUTHUPADY",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "DAYAPURAM ARTS & SCIENCE COLLEGE FOR WOMEN,DAYAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "DON BOSCO COLLEGE MAMPETTA MUKKAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    dept: "BA ECONOMICS WITH DEVELOPMENT ECONOMICS",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "DR.B.R.AMBEDKAR MEMORIAL GOVT.ARTS & SCIENCE COLLEGE BALUSERRY",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "EDUCOS ARTS & SCIENCE COLLEGE,KUTTIYADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "48.00%",
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "BA POLITICAL ADMINISTRATION",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "BA PUBLIC ADMINISTRATION",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "GOLDEN HILLS ARTS & SCIENCE COLLEGE,ELETTIL,VALIYAPARAMBA,KODUVALLY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    dept: "B.Com FINANCE",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KUNNAMANGALAM",
    dept: "BA ECONOMICS WITH DEVELOPMENT ECONOMICS",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "ARABIC & HISTORY DOUBLE MAIN",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "BA HINDI LANGUAGE & LITRATURE",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MEENCHANDA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,KODENCHERY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "47.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "BA POLITICAL ADMINISTRATION",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MADAPPALLY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,MOKERI",
    dept: "BA ECONOMETRICS & DATA MANAGEMENT",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "GOVT.ARTS & SCIENCE COLLEGE,NADAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "GURUDEVA COLLEGE OF ADVANCED STUDIES,KOYLANDI",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "HI-TECH ARTS & SCIENCE COLLEGE,VATTOLI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "B.Sc HOTEL MANAGEMENT & CATERING SCIENCE",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "HOLY CROSS INSTITUTE OF MANAGEMENT & TECH,EAST NADAKKAVU",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "BA MASS COMMUNICATION AND JOURNALISM",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "BA ARABIC LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: "76.00%",
  },
  {
    name: "IDEAL COLLEGE OF ARTS & SCIENCE,KUTTIYADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "ILAHIYA ARTS & SCIENCE COLLEGE,KOYLANDY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "JALALIYA WOMEN'S ARABIC COLLEGE,KUTTIKKATUR",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "76.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc BIOTECHNOLOGY",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.Sc HOTEL MANAGEMENT & CATERING SCIENCE",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "BA MULTIMEDIA",
    location: "CALICUT",
    gpa: "47.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.COM COOPERATION",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "JDT ISLAM COLLEGE OF ARTS & SCIENCE VELIMADUKUNNU",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "K.M.O.ARTS & SCIENCE COLLEGE,KODUVALLY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "KADATHANAD ARTS & SCIENCE COLLEGE,MANDARATHUR,VADAKARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "KMCT ARTS & SCIENCE COLLEGE,MANASSERY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "LITTLE FLOWERS INSTITUTE OF SOCIAL SCIENCE & HEALTH,KAITHAPOYIL",
    dept: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "M.DASAN ARTS & SCIENCE COLLEGE ULLIYERI",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Sc COSTUME & FASHION DESIGNING",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "M.E,S ARTS & SCIENCE COLLEGE,CHATHAMANGALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "M.E.S COLLEGE VADAKARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "76.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "M.E.T COLLEGE OF ARTS & SCIENCE,NADAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "MAHLARA ARTS & SCIENCE COLLEGE FOR WOMEN,MAVOOR",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "48.00%",
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "BACHELOR OF SOCIAL WORK",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "MALABAR ARTS & SCIENCE FOR WOMEN,CHEKKIAD,NADAPURAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BA ECONOMICS ",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "MALABAR CHRISTIAN COLLEGE,CALICUT",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "MALABAR COLLEGE OF ARTS & SCIENCE,MOODADI",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "MARKAZ COLLEGE OF ARTS & SCIENCE,KUNNAMANGALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "MH COLLEGE OF ARTS & SCIENCE,KUTTIYADY",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.SC BIOCHEMISTRY",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "MHES COLLEGE OF SCIENCE & TECHNOLOGY,VADAKARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.SC POLYMER CHEMISTRY",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.SC MICROBIOLOGY",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "MUHAMMED ABDUL RAHIMAN MEMORIAL ORPHANAGE COLLEGE,MUKKOM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    dept: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "MUSLIM ORPHANAGES COLLEGE OF ARTS & SCIENCE,PARAMBADAM,CHERUVATTA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "B.SC BIOCHEMISTRY",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "NATIONAL COLLEGE OF ARTS & SCIENCE,PULIYAVU,PARAKKADAVU",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "58.00%",
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "P V S COLLEGE OF ARTS & SCIENCE PANTHEERANKAVU",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "47.00%",
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "55.00%",
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "PEEKAY CICS ARTS & SCIENCE COLLEGE,MATHARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "49.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA TRAVEL & TOURISM MANAGEMENT",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "76.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "PROVIDENCE WOMEN’S COLLEGE,MALAPARAMBA",
    dept: "BA HRM",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "45.00%",
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "R.SANKARA MEMORIAL SNDP YOGAM ARTS & SCIENCE COLLEGE,KOYILANDY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "RAHMANIYA ARABIC COLLEGE,KATAMERI",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "48.00%",
  },
  {
    name: "RAHMANIYA ARABIC COLLEGE,KATAMERI",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "ROUZATHUL ULOOM ARABIC COLLEGE,PO FAROOK COLLEGE",
    dept: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "SI WOMENS COLLEGE OF ARTS AND SCIENCE,PARAKKADAVU",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "43.00%",
  },
  {
    name: "S.M.I ARTS & SCIENCE COLLEGE,KUNHIPPALLY",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "SALAFIYYA ARABIC COLLEGE COLLEGE,MEPPAYUR",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "SAQAFATHUL ISLAM ARABIC COLLEGE,PARAKKADAVU",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "B.SC FAMILY & COMMUNITY SCIENCE",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "SAVITHRI DEVI SABOO MEMORIAL WOMEN’S COLLEGE,VELLANUR",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "73.00%",
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "59.00%",
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "SILVER ARTS & SCIENCE COLLEGE,PERAMBRA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "47.00%",
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "SNES COLLEGE OF ARTS COMMERCE & MANAGEMENT,KUNNAMANGALAM",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "70.00%",
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "48.00%",
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc GEOLOGY",
    location: "CALICUT",
    gpa: "42.00%",
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc FOOD TECHNOLOGY",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "SREE GOKULAM ARTS & SCIENCE COLLEGE,KOOTALIDA,BALUSSERY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "52.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc STATISTICS",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "56.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "75.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Sc COMPUTER SCIENCE",
    location: "CALICUT",
    gpa: "72.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "79.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "SREE NARAYANA COLLEGE,VATAKARA",
    dept: "B.Com CO-OPERATION",
    location: "CALICUT",
    gpa: "50.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "62.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "64.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE OF ADVANCED STUDIES,CHELANNUR",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "67.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "63.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "78.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "BA MALAYALAM LANGUAGE & LITARTURE",
    location: "CALICUT",
    gpa: "68.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "41.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "SREE NARAYANA GURU COLLEGE,CHELANNUR",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "BA SOCIOLOGY",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "BA FUNCTIONAL ENGLISH",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "74.00%",
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "B.Sc PSYCHOLOGY",
    location: "CALICUT",
    gpa: "57.00%",
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "ST XAVIERS ARTS & SCIENCE COLLEGE,ERANHIPALAM",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "SUNNIYA ARABIC COLLEGE,CHENNAMANGALUR",
    dept: "BA AFSAL-UL-ULAMA",
    location: "CALICUT",
    gpa: "60.00%",
  },
  {
    name: "SUNNIYA ARABIC COLLEGE,CHENNAMANGALUR",
    dept: "B.Com WITH ISLAMIC FINANCE",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "71.00%",
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "44.00%",
  },
  {
    name: "SYED ABDUL RAHIMAN BAFAKHY THANGAL MEMORIAL GOVT COLLEGE,KOYLANDY",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "77.00%",
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "46.00%",
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "47.00%",
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    dept: "BACHELOR OF COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "69.00%",
  },
  {
    name: "V.K.H.M.O COLLEGE OF ARTS & SCIENCE COLLEGE FOR WOMEN",
    dept: "B.Com COMPUTER APPLICATION",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA ENGLISH LANGUAGE & LITERATURE",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA ECONOMICS",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA HISTORY",
    location: "CALICUT",
    gpa: "53.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA MALAYALAM LANGUAGE & SOCIOLOGY DOUBLE MAIN",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BA HINDI LANGUAGE & SOCIOLOGY DOUBLE MAIN",
    location: "CALICUT",
    gpa: "51.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "BACHELOR OF BUSINESS ADMINISTRATION",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc ZOOLOGY",
    location: "CALICUT",
    gpa: "61.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc PHYSICS",
    location: "CALICUT",
    gpa: "65.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc MATHEMATICS",
    location: "CALICUT",
    gpa: "54.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc BOTANY",
    location: "CALICUT",
    gpa: "80.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.Sc CHEMISTRY",
    location: "CALICUT",
    gpa: "66.00%",
  },
  {
    name: "ZAMORIANS GURUVAYURAPPAN COLLEGE,CALICUT",
    dept: "B.CoM FINANCE",
    location: "CALICUT",
    gpa: "60.00%",
  },
];

export default colleges;
